"""Add forensic acquisition manifest fields

Revision ID: 6161617ab2f3
Revises: 4a2248aabb20
Create Date: 2026-09-27 07:56:31.524980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6161617ab2f3'
down_revision: Union[str, Sequence[str], None] = '4a2248aabb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acquisitions', sa.Column('acquired_size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('acquisitions', sa.Column('sector_size', sa.Integer(), nullable=True))
    op.add_column('acquisitions', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('acquisitions', sa.Column('vendor', sa.String(length=100), nullable=True))
    op.add_column('acquisitions', sa.Column('device_model', sa.String(length=100), nullable=True))
    op.add_column('acquisitions', sa.Column('source_filesystem', sa.String(length=100), nullable=True))
    op.add_column('acquisitions', sa.Column('hash_algorithm', sa.String(length=20), nullable=True))
    op.add_column('acquisitions', sa.Column('tool_version', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acquisitions', 'tool_version')
    op.drop_column('acquisitions', 'hash_algorithm')
    op.drop_column('acquisitions', 'source_filesystem')
    op.drop_column('acquisitions', 'device_model')
    op.drop_column('acquisitions', 'vendor')
    op.drop_column('acquisitions', 'source_type')
    op.drop_column('acquisitions', 'sector_size')
    op.drop_column('acquisitions', 'acquired_size_bytes')
    # ### end Alembic commands ###
